version: '3'
services:
  # app containers
  reporting:
    build:
      context: .
      dockerfile: reporting/Dockerfile
    volumes:
      - ./reportingapi/:/app/reportingapi
      - ./reporting/:/app/reporting
    ports:
      - '8080:8080'
    depends_on:
      - rabbitmq
      - mongo
  reporting-gateway:
    build:
      context: .
      dockerfile: reporting-gateway/Dockerfile
    volumes:
      - ./reportingapi/:/app/reportingapi
      - ./reporting-gateway/:/app/reporting-gateway
    ports:
      - '8081:8081'
    depends_on:
      - rabbitmq
      - mongo

  # utility containers
  prom:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - '3000:3000'
    depends_on:
      - prom
  rabbitmq:
    image: rabbitmq:management
  mongo:
    image: mongo:xenial
    ports:
      - "27017:27017"

  #ELK Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local